##### CreateNewUser 
POST http://localhost:3003/users/createNewUser 
Content-Type: : application/json // cria uma conta para o cliente

{
"name":"Fulana", "CPF": "123.456.789-98", "birthDateAsString": "02/02/2002"
}


##### GetAllUsers 
GET http://localhost:3003/users/all // Busca todos os usuários

#####
